Homework 3 css
SomeArtem/ITMO_projects_Serebryakov pull request #4
Opened 2023-03-18 22:32 UTC by SomeArtem

-Responsible product card added
-Repo converted to private

2023-03-21 17:43 UTC, SomeArtem commented
@VladimirCores ВЛАДИМИР! ПОЖАЛУЙСТА, СДЕЛАЙТЕ РЕВЬЮ :D

2023-03-22 20:00 UTC, VladimirCores requested changes

2023-03-22 20:00 UTC, VladimirCores commented on public/style.css
> +.prices{
Пропушен пробел.

2023-03-22 20:00 UTC, VladimirCores commented on public/style.css
> +.btn_icon{
Опять пропушен пробел.

2023-03-24 13:03 UTC, SomeArtem commented
@VladimirCores Пробелы в домашке css добавлены!

2023-03-24 18:01 UTC, VladimirCores approved these changes
Посмотрел, все хорошо!

2023-04-02 11:54 UTC, merged